name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
      - 'pnpm-lock.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20.9.*
            cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build --filter=api
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            workingDirectory: apps/api
            command: |
                pages deploy dist --project-name=hi-restaurant-api



